/**:
  ros__parameters:
    drive_timer_period: 0.25
    drive_linear: 0.0
    drive_angular: 0.0
    goal_x: 1.0
    goal_y: 1.0
    robot_namespace_0_goal_x: 3.0
    robot_namespace_0_goal_y: 0.0
    robot_namespace_1_goal_x: 0.0
    robot_namespace_1_goal_y: 0.0
    robot_namespace_2_goal_x: 0.0
    robot_namespace_2_goal_y: 3.0
    robot_namespace_3_goal_x: 3.0
    robot_namespace_3_goal_y: 3.0
    robot_namespace_4_goal_x: 1.5
    robot_namespace_4_goal_y: 1.5

